<h1 align="center">PyTorch</h1>

1. Tensor Computation
2. GPU Acceleration : able to use GPU to speedup calculations
3. Dynamic Computing Graph : can change to execution flow during runtime
4. Automatic Differentiation
5. Distributed Training
6. Interoperability with other libraries



<h3 align="center">Core PyTorch Modules</h3>

- `torch` : the core module providing multidimensional arrays(tensor) and mathematical operations on them.
- `torch.autograd` : automatic differentiation engine that records operations on tensor to compute gradients for optimizations.
- `torch.nn` : provides the nn library, including layers, activations, loss functions and utilities to build deep learning models.
- `torch.optim` : contains optimization algorithms(optimizers) such as SGD, Adam, and RMSprop.
- `torch.utils.data` : used for data handling, including Dataset and Dataloader classes for managing and loading datasets efficiently.
- `torch.jit` : supports JIT compilation and TorchScript for optimizing models and enabling deployment without Python dependencies.
- `torch.distributed` : tolls for distributed training across multiple GPUs and machines, facilitating parallel computation.
- `torch.cuda` : interfaces with NVIDIA CUDA to enable GPU acceleration for tensor computations and model training.
- `torch.backends `: contains settings and allows control over backend libraries like cuDNN, MKL and other performance tuning.
- `torch.multiprocessing` : used for parallelism and multiprocessing similar to python module but with support for CUDA tensors.
- `torch.quantization` : tool for model quantization to reduce model size and improve inference speed, especially on edge devices.
- `torch.onyx `: support exporting PyTorch models like ONNX(Open Neural Network Exchange) format for interoperability with other frameworks and deployment.



In [2]:
import torch

In [2]:
torch.__version__

'2.5.1'

In [9]:
# For CUDA device
if torch.cuda.is_available():
    print(torch.get_device(0))
else:
    print("Nvidia GPU is not available")

# FOR M-Series mac gpu
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print(device)
else:
    print("MPS is not available")


Nvidia GPU is not available
mps


In [10]:
# Tensor can be thought as an n-dimensional array

# zero-dimensional tensor : Scalar
zero_d_tensor = torch.tensor(0)
zero_d_tensor.ndim, zero_d_tensor

(0, tensor(0))

In [11]:
# one-dimensional tensor : Vector

one_d_tensor = torch.tensor([1, 5, 10, 13])
one_d_tensor, one_d_tensor.ndim


(tensor([ 1,  5, 10, 13]), 1)

In [12]:
# two-dimensional tensor: Matrix

# grayscale image can be represented as a 2D tensor where each entry corresponds to the pixel intensity(0-255)
two_d_tensor = torch.tensor([
    [0, 255,128],
    [34, 90, 180]
])

two_d_tensor, two_d_tensor.ndim

(tensor([[  0, 255, 128],
         [ 34,  90, 180]]),
 2)

In [13]:
# three-dimensional tensor: RGB Image
three_d_tensor = torch.tensor([
    [
        [0, 255,128],
        [0, 255,128],
        [0, 255,128]
    ]
], dtype=torch.uint8)

three_d_tensor, three_d_tensor.ndim

(tensor([[[  0, 255, 128],
          [  0, 255, 128],
          [  0, 255, 128]]], dtype=torch.uint8),
 3)

In [14]:
# four-dimensional : Batches of RGB images

four_d_tensor = torch.tensor([[
    [
        [0, 255,128],
        [0, 255,128],
        [0, 255,128]
    ]
]], dtype=torch.uint8)
four_d_tensor, four_d_tensor.ndim

(tensor([[[[  0, 255, 128],
           [  0, 255, 128],
           [  0, 255, 128]]]], dtype=torch.uint8),
 4)

Tensor are useful because:

- Mathematical Operations : linear algebraic operations
- Representation of real-world data as a tensor
- Can be run on gpu and can be parallelized

Tensor used in DL:

- Data Storage
- Weight and Biases
- Matrix Operations
- Training Process :
    -  Forward pass in DL : z(xTw + b) , gradients during backward pass


In [19]:
# check type of tensor

one_d_tensor.dtype

torch.int64

In [18]:
# size of tensor

one_d_tensor.size()

torch.Size([4])

In [31]:
# using empty

empty_tensor = torch.empty(size=(2,3))
print(empty_tensor)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [36]:
# zeros tensor : all the entries of tensor are 0

zero_tensor = torch.zeros(size=(5,5))
print(zero_tensor)

zero_tensor.dtype, zero_tensor.size()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


(torch.float32, torch.Size([5, 5]))

In [37]:
# ones tensor : all the entries of tensor are 1

ones_tensor = torch.ones(size=(5,5))
print(ones_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


By default the data  type in tensor is : `float32`

In [50]:
# rand tensor: entries of the tensor contains randon number between 0 and 1

random_tensor = torch.rand(size=(5,5))
print(random_tensor)

random_tensor.dtype, random_tensor.size()
print("rand(): picks the values(0 to 1) from randomly from uniform distribution.")

tensor([[0.1182, 0.3628, 0.3302, 0.2807, 0.8269],
        [0.7934, 0.1577, 0.6951, 0.9363, 0.3530],
        [0.7394, 0.1078, 0.1731, 0.1845, 0.5970],
        [0.0264, 0.5525, 0.9674, 0.8975, 0.6987],
        [0.2962, 0.7868, 0.6388, 0.3797, 0.8793]])
rand(): picks the values(0 to 1) from randomly from uniform distribution.


Linearly Spaced Tensor : one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.

In [62]:
linearly_spaced_tensor = torch.linspace(start=0, end=10, steps=5)
linearly_spaced_tensor

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

Seeding

In [83]:
# tensor entries will be same
torch.manual_seed(0)

rand_t_seed_0 = torch.rand(size=(5,5))
print(rand_t_seed_0)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194]])


In [85]:
torch.manual_seed(0)

rand_t_seed_0 = torch.rand(size=(5,5))
print(rand_t_seed_0)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194]])


Creating Custom Tensors

In [87]:
arr = [[12, 3, 45], [4,66, 3]]

arr_to_tensor = torch.tensor(arr, dtype=torch.float32)
print(arr_to_tensor), type(arr_to_tensor)

tensor([[12.,  3., 45.],
        [ 4., 66.,  3.]])


(None, torch.Tensor)

Identity Matrix

In [116]:
# diagonal tensor

default_diag_tensor = torch.eye(3,3)
print(default_diag_tensor)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [118]:
# get the diagonal values
x = torch.rand(3,3)
print(x)

diagonal_values = torch.diag(x)
print(diagonal_values)

tensor([[0.8579, 0.6870, 0.0051],
        [0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704]])
tensor([0.8579, 0.7497, 0.9704])


In [127]:
# homogenous tensor

homogenous_tensor = torch.full((3,3), 5)
print(homogenous_tensor)

homogenous_tensor_2 = torch.full((3,3), 10.0)
print(homogenous_tensor_2)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


Creating a tensor with range

In [132]:
range_tensor = torch.arange(0, 10, 2, dtype=torch.float32)
print(range_tensor)

tensor([0., 2., 4., 6., 8.])


Tensor Shapes

In [144]:
x1 = torch.rand(5,5)
print(x1)
x1.shape

tensor([[0.0780, 0.3986, 0.7742, 0.7703, 0.0178],
        [0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
        [0.4018, 0.0513, 0.0683, 0.4218, 0.5065],
        [0.2729, 0.6883, 0.0500, 0.4663, 0.9397],
        [0.2961, 0.9515, 0.6811, 0.0488, 0.8163]])


torch.Size([5, 5])

In [149]:
# want to create a tensor with same shape as x1
same_shape_as_x1 = torch.empty(x1.shape)
print(same_shape_as_x1)

print(torch.full_like(x1, 5))
print(torch.zeros_like(x1))
print(torch.ones_like(x1))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Copying Tensor

In [160]:
# shallow copy

x2 = x1
print(x2)

print(hash(x1) == hash(x2))

x3 = torch.tensor(x1)
print(x3)

print(hash(x1) == hash(x3))

tensor([[0.0780, 0.3986, 0.7742, 0.7703, 0.0178],
        [0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
        [0.4018, 0.0513, 0.0683, 0.4218, 0.5065],
        [0.2729, 0.6883, 0.0500, 0.4663, 0.9397],
        [0.2961, 0.9515, 0.6811, 0.0488, 0.8163]])
True
tensor([[0.0780, 0.3986, 0.7742, 0.7703, 0.0178],
        [0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
        [0.4018, 0.0513, 0.0683, 0.4218, 0.5065],
        [0.2729, 0.6883, 0.0500, 0.4663, 0.9397],
        [0.2961, 0.9515, 0.6811, 0.0488, 0.8163]])
False


/var/folders/7v/vys765k90y9gn_dw0h3w0z5h0000gn/T/ipykernel_28365/4251606690.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x3 = torch.tensor(x1)


In [161]:
# deep copy : true copy

x2 = x1.clone().detach()
print(x2)

print(hash(x1) == hash(x2))

tensor([[0.0780, 0.3986, 0.7742, 0.7703, 0.0178],
        [0.8119, 0.1087, 0.3943, 0.2973, 0.4037],
        [0.4018, 0.0513, 0.0683, 0.4218, 0.5065],
        [0.2729, 0.6883, 0.0500, 0.4663, 0.9397],
        [0.2961, 0.9515, 0.6811, 0.0488, 0.8163]])
False


Tensor Mathematical Operations

In [9]:
x = torch.randint(0, 10, (1,5))
y = torch.randint(10, 20, (1,5))
print("X ", x)
print("Y ", y)
print( x + y )

X  tensor([[3, 2, 2, 7, 9]])
Y  tensor([[12, 14, 12, 18, 12]])
tensor([[15, 16, 14, 25, 21]])


In [10]:
print( x - y )

tensor([[ -9, -12, -10, -11,  -3]])


In [11]:
print( x * y )

tensor([[ 36,  28,  24, 126, 108]])


In [13]:
print( x / y )

tensor([[0.2500, 0.1429, 0.1667, 0.3889, 0.7500]])


In [18]:
# returns 1 if not divisible by 2 else returns 0
print(x % 2)

tensor([[1, 0, 0, 1, 1]])


In [27]:
# transpose
print("Before transpose: ", x)
transpose_x = x.T
print(transpose_x)

print(x.shape, transpose_x.shape)

Before transpose:  tensor([[3, 2, 2, 7, 9]])
tensor([[3],
        [2],
        [2],
        [7],
        [9]])
torch.Size([1, 5]) torch.Size([5, 1])


In [43]:
torch.manual_seed(123)

matrix = torch.randint(0, 5, (3,3))
print(matrix)

v = torch.tensor([-1, 0, 1])

res = torch.matmul(matrix, v)
print("Res: ", res)

tensor([[2, 4, 2],
        [0, 0, 2],
        [1, 2, 4]])
Res:  tensor([0, 2, 3])
