In [1]:
import torch
from mistune.plugins.speedup import speedup
from requests import delete

In [6]:
# Apple M-Series GPU
if torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

In [7]:
device

device(type='mps')

Creating tensor directly on GPU

In [31]:
tensor_on_gpu = torch.randn((1,100), device=device)
print(tensor_on_gpu)

tensor([[-0.6906,  0.6685,  0.5140,  1.1113, -0.4885, -0.8072, -0.1593,  0.3866,
          0.7595, -0.7832,  0.4473, -0.5006,  0.6245,  1.5383,  0.1674,  1.5041,
         -1.8178, -0.5112, -0.2424,  1.7457, -0.4926,  0.8301, -1.2572,  2.0500,
         -0.2235,  1.7821, -0.9370, -0.1011, -1.8279, -0.1539,  1.3939,  0.5859,
          0.3556, -0.1198,  0.4467, -0.6744,  0.6330,  0.4523, -0.8398,  1.3423,
         -0.5747, -0.4229,  0.2360, -0.6424,  0.5872,  1.0378, -0.2401,  0.4329,
          0.2897,  0.8019,  0.8613, -1.9732, -0.2761,  0.2811,  0.4771,  0.1949,
         -0.7711,  0.0787,  0.5961,  1.0704, -0.7727, -0.5376, -0.7488,  0.0812,
          0.7178,  2.1007, -0.3433,  0.3104, -0.2520, -0.0679, -0.3219, -0.0056,
          0.9772,  1.3820,  0.9785,  0.9086, -0.0399,  1.0835, -0.5574,  0.0371,
         -0.5121,  1.0380, -1.2688,  0.6838,  0.0393,  0.1016, -0.1701, -0.1640,
          1.5495, -0.7094, -0.7630, -1.8333, -1.2743, -1.3693, -1.5351, -0.4042,
         -0.9915, -0.1157, -

Loading the tensor from CPU to GPU

In [32]:
tensor_on_cpu = torch.randn(1,100)
print(tensor_on_cpu)

tensor([[ 0.2866,  0.6810,  0.7856, -0.9897,  0.3217, -1.2076, -0.4931, -1.5623,
         -0.9995, -0.5288,  0.1305,  1.8685,  0.0364,  1.1974, -0.0867, -0.3482,
          0.3900,  0.9182, -0.1606, -1.4434,  0.1818, -0.4112,  1.8491, -0.2412,
         -0.8175, -1.5244, -0.2964, -1.5349, -0.3892,  0.8344,  1.4887, -0.6923,
          0.7511, -0.0296, -0.5557,  0.9183, -0.5913, -1.1816, -0.1183,  1.5848,
         -0.8017, -0.0156,  0.0130,  0.2284, -0.3615,  1.0280, -0.6735, -0.8081,
          1.5538, -0.2224,  0.5608, -1.0810, -1.1300,  0.9732,  0.1275, -1.2171,
          1.7618,  0.7645, -1.8044,  0.5261,  0.0326,  0.1956,  0.5222,  0.6699,
         -0.7333, -0.9613, -0.2635, -2.1884, -0.6788, -0.0138, -0.8783, -1.4675,
          0.7742,  0.7288, -0.3964, -0.1791,  0.9307, -1.2816, -1.8383, -0.4697,
          1.4614,  0.4369,  0.0638, -0.2479,  0.7006, -0.9237,  0.3558,  0.1841,
         -0.4641, -0.5300,  0.5422, -0.1667,  0.4780, -0.6419,  0.5543, -1.5321,
          0.7398, -1.1497,  

In [33]:
# load the tensor from cpu to gpu

c = tensor_on_cpu.to(device)
print(c)

tensor([[ 0.2866,  0.6810,  0.7856, -0.9897,  0.3217, -1.2076, -0.4931, -1.5623,
         -0.9995, -0.5288,  0.1305,  1.8685,  0.0364,  1.1974, -0.0867, -0.3482,
          0.3900,  0.9182, -0.1606, -1.4434,  0.1818, -0.4112,  1.8491, -0.2412,
         -0.8175, -1.5244, -0.2964, -1.5349, -0.3892,  0.8344,  1.4887, -0.6923,
          0.7511, -0.0296, -0.5557,  0.9183, -0.5913, -1.1816, -0.1183,  1.5848,
         -0.8017, -0.0156,  0.0130,  0.2284, -0.3615,  1.0280, -0.6735, -0.8081,
          1.5538, -0.2224,  0.5608, -1.0810, -1.1300,  0.9732,  0.1275, -1.2171,
          1.7618,  0.7645, -1.8044,  0.5261,  0.0326,  0.1956,  0.5222,  0.6699,
         -0.7333, -0.9613, -0.2635, -2.1884, -0.6788, -0.0138, -0.8783, -1.4675,
          0.7742,  0.7288, -0.3964, -0.1791,  0.9307, -1.2816, -1.8383, -0.4697,
          1.4614,  0.4369,  0.0638, -0.2479,  0.7006, -0.9237,  0.3558,  0.1841,
         -0.4641, -0.5300,  0.5422, -0.1667,  0.4780, -0.6419,  0.5543, -1.5321,
          0.7398, -1.1497,  

In [36]:
x_gpu = torch.randn((1000,1000), device=device)
y_gpu = torch.randn((1000,1000), device=device)

In [42]:
%%timeit
res = torch.matmul(x_gpu, y_gpu)

558 μs ± 1.16 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [38]:
x_cpu = torch.randn((1000,1000))
y_cpu = torch.randn((1000,1000))

In [43]:
%%timeit
r = torch.matmul(x_cpu, y_cpu)

1.03 ms ± 29 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [46]:
print("GPU speedup : ", 1.03/0.558)

GPU speedup :  1.8458781362007166


As the data size grows the GPU will outperform the CPU by ~100x